### ISSUE TITLE
Trying to build on Ubuntu 16.04, getting a build error[Failure executing javac]

### ISSUE THREAD

**Issue by psingh24** [prometheus/cloudwatch_exporter#118]
Not really sure what is causing the issue. I was following this [tutorial](https://medium.com/@griggheo/initial-experiences-with-the-prometheus-monitoring-system-167054ac439c). Also I apologize for my ignorance I am not very family with Java at all, I couldn't find a good tutorial on how to set up/use your cloudwatch exporter. 

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cloudwatch_exporter 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ cloudwatch_exporter ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cloudwatch_exporter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/prometheus/dist/cloudwatch_exporter/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ cloudwatch_exporter ---
[INFO] Compiling 6 source files to /opt/prometheus/dist/cloudwatch_exporter/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: directory not found: /opt/prometheus/dist/cloudwatch_exporter/target/classes
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.301 s
[INFO] Finished at: 2018-07-03T21:12:45+00:00
[INFO] Final Memory: 10M/31M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project cloudwatch_exporter: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: directory not found: /opt/prometheus/dist/cloudwatch_exporter/target/classes
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by brian-brazil** [comment]
That error is due to your setup. Official releases can be found in the central repository:  http://repo1.maven.org/maven2/io/prometheus/cloudwatch/cloudwatch_exporter/0.1.0/
